Finish custom files in .config

diff --git a/.config/shell/aliasrc b/.config/shell/aliasrc
--- a/.config/shell/aliasrc
+++ b/.config/shell/aliasrc
@@ -48,7 +48,18 @@ alias \
 	sdn="shutdown -h now" \
 	e="$EDITOR" \
 	v="$EDITOR" \
+	ps="p -Ss" \
+	prfz="pacman -Qq | fzf --multi --preview 'pacman -Qi {1}' | xargs -ro sudo pacman -Rns" \
 	p="pacman" \
+	pi="p -S" \
+	pup="p -Syu" \
+	ys="y -Ss" \
+	yfz="yay -Slq | fzf --multi --preview 'yay -Si {1}' | xargs -ro sudo yay -S" \
+	yrfz="yay -Qq | fzf --multi --preview 'yay -Qi {1}' | xargs -ro sudo yay -Rns" \
+	y="yay" \
+	yi="y -S" \
+	yup="y -Syu" \
+	t="template" \
 	xi="sudo xbps-install" \
 	xr="sudo xbps-remove -R" \
 	xq="xbps-query" \
@@ -59,3 +70,24 @@ alias \
 	magit="nvim -c MagitOnly" \
 	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc" \
 	weath="less -S ${XDG_CACHE_HOME:-$HOME/.cache}/weatherreport" \
+	ports="sudo lsof -i -P -n | grep LISTEN" \
+	handbrake="ghb"
+
+up () {
+	local d=""
+	local limit="$1"
+
+	#Default to limit of 1
+	if [ -z "$limit" ] || [ "$limit" -le 0 ]; then
+		limit=1
+	fi
+
+	for ((i=1;i<=limit;i++)); do
+		d="../$d"
+	done
+
+	#perform cd. Show error if cd fails.
+	if ! cd "$d"; then
+		echo "Couldn't go up $limit dirs.";
+	fi
+}
